version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run: sudo composer self-update --2
      - run: cd src && composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: php artisan test tests/Feature/ItemControllerTest.php